Add #[must_use] to switches
Switches just contain values and have no side effects. Thus, building a
value of this type and not using it makes no sense.

Also, this fixes a clippy warning:

error: missing `#[must_use]` attribute on a method returning `Self`
    --> src/protocol/xproto.rs:5649:5
     |
5649 | /     pub fn event_mask<I>(mut self, value: I) -> Self where I: Into<Option<u32>> {
5650 | |         self.event_mask = value.into();
5651 | |         self
5652 | |     }
     | |_____^
     |
     = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#return_self_not_must_use

Fixes: https://github.com/psychon/x11rb/issues/652
Signed-off-by: Uli Schlachter <psychon@znc.in>