Fix our msrv-check build
The build fails with:

    error: package `tracing-core v0.1.34` cannot be built because it
    requires rustc 1.65.0 or newer, while the currently active rustc
    version is 1.64.0

Signed-off-by: Uli Schlachter <psychon@znc.in>