Remove AppVeyor integration
For a while now, AppVeyor builds were randomly failing with random error
messages at random points. They seem to indicate some kind of TLS error. For
example:

    warning: spurious network error (1 tries remaining): [35] SSL connect error (schannel: next InitializeSecurityContext failed: SEC_E_ILLEGAL_MESSAGE (0x80090326) - This error usually occurs when a fatal SSL/TLS alert is received (e.g. handshake failed). More detail may be available in the Windows System event log.)
    error: failed to download from `https://crates.io/api/v1/crates/matchers/0.1.0/download`
    Caused by:
      [35] SSL connect error (schannel: next InitializeSecurityContext failed: SEC_E_ILLEGAL_MESSAGE (0x80090326) - This error usually occurs when a fatal SSL/TLS alert is received (e.g. handshake failed). More detail may be available in the Windows System event log.)

In commit fa6fc845a71c, I already added a Windows build to GitHub
actions. This commit finishes the conversion by removing "everything
AppVeyor".

I also removed all required status checks from .mergify.yml and not just
the AppVeyor one. The reason for this is that I already configured
GitHub branch protection rules and Mergify automatically picks this up.
I find this easier to manage than having an explicit list of checks in
this file. The downside is of course that changes a more secretive and
not tracked in Git. I hope that's okay.

Signed-off-by: Uli Schlachter <psychon@znc.in>