Avoid image 0.24.3
It does not build with Rust 1.46:

  Downloaded image v0.24.3
error: failed to parse manifest at `/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.24.3/Cargo.toml`

Caused by:
  feature `resolver` is required

  this Cargo does not support nightly features, but if you
  switch to nightly channel you can add
  `cargo-features = ["resolver"]` to enable this feature

Signed-off-by: Uli Schlachter <psychon@znc.in>