Fix some errors in xkb
The generated code did not compile. Example build errors are:

error[E0308]: mismatched types
    --> x11rb-protocol/src/protocol/xkb.rs:6635:66
     |
6635 |         let details_bytes = self.details.serialize(affect_which, self.clear, self.select_all);
     |                                                                  ^^^^^^^^^^ expected `u16`, found struct `EventType`

error[E0308]: mismatched types
    --> x11rb-protocol/src/protocol/xkb.rs:6635:78
     |
6635 |         let details_bytes = self.details.serialize(affect_which, self.clear, self.select_all);
     |                                                                              ^^^^^^^^^^^^^^^ expected `u16`, found struct `EventType`

This commit introduces mostly useless conversions to work around this problem.

Signed-off-by: Uli Schlachter <psychon@znc.in>