Silence a clippy warning from v1.59
When building without features, this variable is unused and clippy wants to
change the argument type, but that's only possible because of the disabled
features, thus we cannot do that.

error: writing `&mut Vec` instead of `&mut [_]` involves a new object where a slice will do
    --> src/protocol/mod.rs:1275:14
     |
1275 |         fds: &mut Vec<RawFdContainer>,
     |              ^^^^^^^^^^^^^^^^^^^^^^^^ help: change this to: `&mut [RawFdContainer]`
     |
     = note: `-D clippy::ptr-arg` implied by `-D warnings`
     = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#ptr_arg

Signed-off-by: Uli Schlachter <psychon@znc.in>