Fix some more new clippy warnings in tests
error: calls to `push` immediately after creation
   --> tests/regression_tests.rs:184:5
    |
184 | /     let mut expected = Vec::new();
185 | |     expected.push(x11rb::protocol::xproto::POLY_SEGMENT_REQUEST);
186 | |     expected.push(0); // padding
    | |_____________________^ help: consider using the `vec![]` macro: `let mut expected = vec![..];`
    |
    = note: `-D clippy::vec-init-then-push` implied by `-D warnings`
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#vec_init_then_push

Signed-off-by: Uli Schlachter <psychon@znc.in>