Fix "cargo test" doctests
A wrong/old crate name was used in a doc test.

---- src/protocol/xproto.rs - protocol::xproto::GetPropertyReply::value16 (line 8909) stdout ----
error[E0433]: failed to resolve: use of undeclared crate or module `x11rb`
 --> src/protocol/xproto.rs:8911:13
  |
4 | let reply = x11rb::protocol::xproto::GetPropertyReply {
  |             ^^^^^ use of undeclared crate or module `x11rb`

Signed-off-by: Uli Schlachter <psychon@znc.in>