Fix new clippy mismatched_lifetime_syntaxes warnings
Example:

```
error: hiding a lifetime that's elided elsewhere is confusing
  --> x11rb/tests/regression_tests.rs:67:9
   |
67 |         &self,
   |         ^^^^^ the lifetime is elided here
...
70 |     ) -> Result<Cookie<Self, R>, ConnectionError>
   |                 --------------- the same lifetime is hidden here
   |
   = help: the same lifetime is referred to in inconsistent ways, making the signature confusing
   = note: `-D mismatched-lifetime-syntaxes` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(mismatched_lifetime_syntaxes)]`
help: use `'_` for type paths
   |
70 |     ) -> Result<Cookie<'_, Self, R>, ConnectionError>
   |                        +++
```

Signed-off-by: Uli Schlachter <psychon@znc.in>