Fix some compile errors in xkb's expression evaluation
error[E0599]: no method named `count_ones` found for struct `SetOfGroup` in the current scope
    --> x11rb-protocol/src/protocol/xkb.rs:8812:76
     |
1107 | pub struct SetOfGroup(u8);
     | -------------------------- method `count_ones` not found for this
...
8812 |         assert_eq!(self.group_rtrn.len(), usize::try_from(self.groups_rtrn.count_ones()).unwrap(), "`group_rtrn` has an incorrect length");
     |                                                                            ^^^^^^^^^^ method not found in `SetOfGroup`

error[E0599]: no method named `count_ones` found for struct `SetOfGroup` in the current scope
    --> x11rb-protocol/src/protocol/xkb.rs:8877:71
     |
1107 | pub struct SetOfGroup(u8);
     | -------------------------- method `count_ones` not found for this
...
8877 |         assert_eq!(self.group_maps.len(), usize::try_from(self.groups.count_ones()).unwrap(), "`group_maps` has an incorrect length");
     |                                                                       ^^^^^^^^^^ method not found in `SetOfGroup`

This commit fixes that by introducing explicit conversions to u32.

Signed-off-by: Uli Schlachter <psychon@znc.in>