parent c358b65d21269b46418dcb7b12c39bd0677ec1e8 author not_a_seagull <notaseagull048@gmail.com> 1647888692 -0700 committer not_a_seagull <notaseagull048@gmail.com> 1647888705 -0700
Move id_allocator and parse_display to the protocol crate

Commit rest of changes

Add some missing docs

Signed-off-by: Uli Schlachter <psychon@znc.in>

Copy #![forbid]s to x11rb-protocol

This commit copies the #![forbid]s and #![deny]s from src/lib.rs to
x11rb-protocol/src/lib.rs.

There is one small change: unsafe_code is unconditionally forbidden in
x11rb-protocol. In x11rb, this depends on the "allow-unsafe-code"
feature.

Signed-off-by: Uli Schlachter <psychon@znc.in>

Add a mechanism to send requests based on traits

Commit 105c0fc3af added three new traits that allow to send a request
simply based on a trait. This commit extends our RequestConnection trait
with functions that use this capability to actually send a request.

For a request which has a reply without FDs, the reply type has to
implement TryParse, but before this commit, the trait only provided
TryParseFd. Thus, this commit moves the "Reply" associated type around
so that only for ReplyFDsRequest it has to implement TryParseFd.

Signed-off-by: Uli Schlachter <psychon@znc.in>

Remove "Reply" field from "Request" trait

The previous commit added a "Reply" associated type to the
"ReplyRequest" trait. Now, both "Request" and "ReplyRequest" have such
an associated type with a different type. To clean that up, this commit
moves Request::Reply to ReplyRequest::Reply. The code generator is
patched up accordingly.

Additionally, Request::parse_reply() is removed. Instead, the same
functionality is implemented in x11rb-protocol/src/protocol/mod.rs
locally (and not "pub"lically), which is the only place where this was
used before.

Signed-off-by: Uli Schlachter <psychon@znc.in>

Remove unnecessary send_foo methods

Once upon a time, each request struct had an associated method "send()"
that allowed to send the request over an X11 connection.

Commit 8aac79fbe0f split the code up so that there is now a
x11rb-protocol and an x11rb crate. The request struct belongs into
x11rb-protocol, but the "send()" method into x11rb. Thus, said commit
replaced the associated functions with just a normal, non-"pub"
function.

This extra, non-public function however only ever had a single caller.
Thus, this commit gets rid of this function and inlines it into its only
caller.

Also: "send()" is no longer necessary. The previous commits added a
possibility to send a request based on the ReplyRequest and
ReplyFDsRequest traits. These new capabilities fully replace the old
"send()" methods.

Signed-off-by: Uli Schlachter <psychon@znc.in>

Fix compilation without all features

error: function is never used: `parse_reply_fds`
  --> x11rb-protocol/src/protocol/mod.rs:25:4
   |
25 | fn parse_reply_fds<'a, R: ReplyFDsRequest>(bytes: &'a [u8], fds: &mut Vec<RawFdContainer>) -> Result<(Reply, &'a [u8]), ParseError> {
   |    ^^^^^^^^^^^^^^^
   |
   = note: `-D dead-code` implied by `-D warnings`

Signed-off-by: Uli Schlachter <psychon@znc.in>

Fix CI build

I had two open PRs at the same time. One added some #[deny]s and the
other one changed lots of code. The result was (after merging both PRs)
ten errors, all looking like this:

error: hidden lifetime parameters in types are deprecated
    --> x11rb-protocol/src/protocol/mod.rs:2149:66
     |
2149 |             Request::InternAtom(_) => Some(parse_reply::<xproto::InternAtomRequest>),
     |                                                                  ^^^^^^^^^^^^^^^^^ expected named lifetime parameter
     |
note: the lint level is defined here
    --> x11rb-protocol/src/lib.rs:7:5
     |
7    |     rust_2018_idioms,
     |     ^^^^^^^^^^^^^^^^
     = note: `#[forbid(elided_lifetimes_in_paths)]` implied by `#[forbid(rust_2018_idioms)]`
help: consider using the `'_` lifetime
     |
2149 |             Request::InternAtom(_) => Some(parse_reply::<xproto::InternAtomRequest<'_>>),
     |                                                                  ~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Uli Schlachter <psychon@znc.in>

Add docs to new items

rustfmt

Move id_allocator outside of protocol impl