Decouple xauth::Family and xproto::Family
Clippy is unhappy about Family having a variant X11Family:

error: Variant name ends with the enum's name
  --> src/rust_connection/xauth.rs:14:5
   |
14 |     X11Family(X11Family),
   |     ^^^^^^^^^^^^^^^^^^^^
   |
   = note: `-D clippy::enum-variant-names` implied by `-D warnings`
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#enum_variant_names

This commit works around that by replacing the X11Family(X11Family) variant
with one variant per possible variant of X11Family. Thus, Family no longer can
contain an X11Family, but instead duplicates its variants.

Signed-off-by: Uli Schlachter <psychon@znc.in>