Bump minimum serde version
Thanks to the previous commit, the msrv-check actually tries to build
serde 1.0.0. This fails with various error messages, among them

    error[E0554]: `#![feature]` may not be used on the stable release
    channel

In this commit, I increase the minimum serde version to 1.0.96. Why this
version? This is the first version where the build actually passes.

Serde 1.0.96 is from 2019 and since previous versions did not build for
me with Rust 1.68 (which is from 2023), I do not think this actually
really bumps anything.

Signed-off-by: Uli Schlachter <psychon@znc.in>