Fix syn v2 pinning in msrv workflow
The msrv-check workflow started failing due to a new syn release.
Updating this script to 2.0.118 just means that things will fail again
after the next syn release. Instead, I noticed that we only depend on
syn v1 through the cairo-example package. That package is not built in
msrv-check anyway, so just removing it from Cargo.toml means we should
only have one syn version in our dependency tree, solving the ambiguity.

Error output was:

    $ cargo update --package syn@2.0.117 --precise 2.0.114
    error: package ID specification `syn@2.0.117` did not match any packages
    Did you mean one of these?

      syn@1.0.109
      syn@2.0.118

Signed-off-by: Uli Schlachter <psychon@znc.in>