Fix syn v2 pin in msrv workflow
The msrv-check workflow started failing due to a new syn release. Sadly,
I do not have a good idea how to fix this so that it does not break
again with the next release of syn, so I just update the version number.

Output was:

    $ cargo update --package syn@2.0.117 --precise 2.0.114
    error: package ID specification `syn@2.0.117` did not match any packages
    Did you mean one of these?

      syn@1.0.109
      syn@2.0.118

Signed-off-by: Uli Schlachter <psychon@znc.in>