Pin last working syn version in msrv-check
See https://github.com/dtolnay/syn/commit/92a0aa4096e5938025eb643312f2394547cae3f4

A first version if this failed with the following, so the exact version to
update is specified:

error: There are multiple `syn` packages in your project, and the specification `syn` is ambiguous.
Please re-run this command with `-p <spec>` where `<spec>` is one of the following:
  syn@1.0.109
  syn@2.0.117

Signed-off-by: Uli Schlachter <psychon@znc.in>