Fix new unused result warning
The nightly build started failing with the following message:

error: unused result of type `((), ())`
  --> xtrace-example/src/main.rs:91:5
   |
91 |     futures_util::try_join!(future1, future2)?;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Signed-off-by: Uli Schlachter <psychon@znc.in>