Fix compilation
The previous revert caused a compiler failure due to an API change that
happened in commit 4399db7eb20:

    error[E0107]: struct takes 0 lifetime arguments but 1 lifetime argument was supplied
        --> x11rb/src/xcb_ffi/mod.rs:649:34
         |
    649  |     for crate::protocol::xproto::WindowWrapper<'_, XCBConnection>
         |                                  ^^^^^^^^^^^^^ -- help: remove the lifetime argument
         |                                  |
         |                                  expected 0 lifetime arguments
         |
    note: struct defined here, with 0 lifetime parameters
        --> x11rb/src/protocol/xproto.rs:5562:12
         |
    5562 | pub struct WindowWrapper<C: RequestConnection>(C, Window);
         |            ^^^^^^^^^^^^^

Signed-off-by: Uli Schlachter <psychon@znc.in>