Fix build of xf86vidmode
This just removes an optimisation and introduces useless calls to
From::from(). However, xf86vidmode has one case where this actually
makes a difference.

In the future, this optimisation might be re-introduced. For now I am
lazy and just want things to compile again.

Build failure was:

error[E0369]: no implementation for `ClockFlag & u32`
    --> x11rb-protocol\src\protocol\xf86vidmode.rs:2341:82
     |
2341 | ...   assert_eq!(self.clock.len(), usize::try_from(1u32.checked_sub(self.flags & 1u32).unwrap().checked_mul(self.clocks).unwrap()).unwrap...
     |                                                                     ---------- ^ ---- u32
     |                                                                     |
     |                                                                     ClockFlag
     |
note: an implementation of `BitAnd<_>` might be missing for `ClockFlag`
    --> x11rb-protocol\src\protocol\xf86vidmode.rs:111:1
     |
111  | pub struct ClockFlag(u32);
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^ must implement `BitAnd<_>`
note: the following trait must be implemented
error[E0308]: mismatched types

Signed-off-by: Uli Schlachter <psychon@znc.in>