Remove unused field in example
This fixes the following clippy warning:

error: field is never read: `height`
  --> examples/simple_window_manager.rs:27:5
   |
27 |     height: u16,
   |     ^^^^^^^^^^^
   |
   = note: `-D dead-code` implied by `-D warnings`

Signed-off-by: Uli Schlachter <psychon@znc.in>