generator: trim() each line of doc <description>
We only removed trailing whitespace from <description> tags. However,
the new xcb-proto version introduced multi-line documentation with
leading tabs. This trips up rustdoc:

error: using tabs in doc comments is not recommended
   --> x11rb-protocol/src/protocol/composite.rs:269:5
    |
269 | ///     storage.  When all clients enabling redirection terminate,
    |     ^^^^ help: consider using four spaces per tab
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#tabs_in_doc_comments
    = note: `-D clippy::tabs-in-doc-comments` implied by `-D warnings`

Fix this by also trimming leading whitespace.

Signed-off-by: Uli Schlachter <psychon@znc.in>