Add a test capturing a bug in x11rb-async
We got a bug report about large requests not being written to the
stream. I managed to trace this down to a bug in WriteBuffer: Trying to
send something larger than the buffer size silently does nothing due to
a logic bug.

This commit adds a test that reproduces the problem. This test currently
fails with:

---- connection_sends_large_request stdout ----
thread 'connection_sends_large_request' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `32768`', x11rb-async/tests/connection_regression_tests.rs:84:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Related-to: https://github.com/psychon/x11rb/issues/810
Signed-off-by: Uli Schlachter <psychon@znc.in>