Fix unused_qualifications warnings on Windows
I am not quite sure why, but CI started failing on windows. The
previous, successful build used Rust 1.77.2 and now with 1.78.0, the
build fail. I do not know whether this is really the reason, but it is
my best guess.

The compiler error message looks like this:

    error: unnecessary qualification
       --> x11rb\src\rust_connection\stream.rs:430:47
        |
    430 |                     Err(ref e) if e.kind() == std::io::ErrorKind::Interrupted => {}
        |                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        |
    note: the lint level is defined here
       --> x11rb\src\lib.rs:129:5
        |
    129 |     unused_qualifications,
        |     ^^^^^^^^^^^^^^^^^^^^^

Signed-off-by: Uli Schlachter <psychon@znc.in>