Update crate dependencies
This updates all dependencies to their latest version, with one
exception. Updating gethostname to the latest version failed to build
locally:

  error: package `gethostname v0.4.1` cannot be built because it
  requires rustc 1.64 or newer, while the currently active rustc version
  is 1.63.0

Signed-off-by: Uli Schlachter <psychon@znc.in>