generator/: Silence some "field is never read" warnings
Example:

error: field is never read: `error`
  --> generator/src/main.rs:44:9
   |
44 |         error: xcbgen::ParseError,
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^

These fields are only "implicitly" via #[derive(Debug)], but they should
be kept for that output. Thus, this commit renames the fields from
"error" to "_error".

Signed-off-by: Uli Schlachter <psychon@znc.in>